gRPC interface implementation for the discord and email provider
ClubCedille/calidum-rotae-backend pull request #5
Opened 2022-02-13 20:55 UTC by ThomasCardin

- Implemented the `SendMessage` function that is going to communicate with the client

2022-02-27 20:47 UTC, ThomasCardin commented
@cguertin14

2022-03-03 14:54 UTC, cguertin14 requested changes

2022-03-03 14:54 UTC, cguertin14 commented on cmd/discord-provider/main.go
> +}
this part should be in a separate Go file, same for other gRPC servers

2022-03-03 14:54 UTC, cguertin14 commented on cmd/email-provider/main.go
> +}
same here

2022-03-09 01:17 UTC, ThomasCardin commented
Thanks for the review @cguertin14! I will check this out ASAP.

2022-03-09 01:19 UTC, cguertin14 commented
> Thanks for the review @cguertin14! I will check this out ASAP.

No rush 🤘🏻

2022-04-09 01:09 UTC, cguertin14 approved these changes

2022-04-09 01:10 UTC, merged